# frozen_string_literal: true

# Provide a description
if github.pr_body.length < 10
  raise 'Please provide a short summary in the PR description :page_with_curl:'
end

# The title should follow conventional commits unless is a dependabot PR
if github.pr_labels.include?('dependencies')
  message 'PR autogenerated by dependabot'
end

message('One approval required for merging')